-- VERIFICAR QUANTOS MÉDICOS EXISTEM EM HOSPITAIS COM MAIS DE DOIS MÉDICOS. 
SELECT H.NOME, COUNT(M.CPF)
FROM MEDICO M INNER JOIN
	HOSPITAL H ON M.CNES_MEDICO = H.CNES_HOSPITAL
GROUP BY H.NOME
HAVING COUNT(*) > 2