CREATE TABLE HOSPITAL(
    CNES_HOSPITAL VARCHAR2(20),
    NOME VARCHAR2(20),
    CEP VARCHAR2(8),
    LOGRADOURO VARCHAR2(100),
    CONSTRAINT HOSPITAL_PKEY PRIMARY KEY (CNES_HOSPITAL)
);
/
CREATE TABLE ATENDENTE (
    CPF VARCHAR2(11),
    RAMAL VARCHAR2(3),
    NOME VARCHAR2(20),
    DATA_NASC DATE,
    CNES_ATENDENTE VARCHAR2(20) NOT NULL,
    CONSTRAINT ATENDENTE_PKEY PRIMARY KEY (CPF),
    CONSTRAINT ATENDENTE_FKEY FOREIGN KEY (CNES_ATENDENTE) REFERENCES HOSPITAL (CNES_HOSPITAL)
);
/

CREATE TABLE PACIENTE (
    CPF VARCHAR2 (11) ,
    NOME VARCHAR2 (20),
    DATA_NASC DATE,
    CPF_ATENDENTE VARCHAR2(11),
    GENERO VARCHAR2(20),
    CONSTRAINT PACIENTE_PKEY PRIMARY KEY (CPF),
    CONSTRAINT PAC_ATEND_FKEY FOREIGN KEY (CPF_ATENDENTE) REFERENCES ATENDENTE (CPF)
);
/
CREATE TABLE MEDICAMENTO(
    LOTE VARCHAR2(60),
    NOME VARCHAR2(20),
    VALIDADE DATE,
    CONSTRAINT MEDICAMENTO_PKEY PRIMARY KEY (LOTE)
);
/

CREATE TABLE ENFERMEIRO(
    CPF VARCHAR2(11),
    CATEGORIA VARCHAR2(20),
    NOME_ENFERMEIRO VARCHAR2(20),
    DATA_NASC DATE,
    CNES_ENFERMEIRO VARCHAR2(20) NOT NULL,
    CONSTRAINT ENFERMEIRO_PKEY PRIMARY KEY (CPF),
    CONSTRAINT ENFERMEIRO_FKEY FOREIGN KEY (CNES_ENFERMEIRO) REFERENCES HOSPITAL(CNES_HOSPITAL)
);
/
CREATE TABLE MEDICO (
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    DATA_NASC DATE,
    ESPECIALIDADE VARCHAR2(25),
    CPF_SUPERVISOR VARCHAR2(11),
    CNES_MEDICO VARCHAR2 (20) NOT NULL,
    CONSTRAINT MEDICO_PKEY PRIMARY KEY (CPF),
    CONSTRAINT MEDICO_FKEY1 FOREIGN KEY (CNES_MEDICO) REFERENCES HOSPITAL (CNES_HOSPITAL),
    CONSTRAINT MEDICO_FKEY2 FOREIGN KEY (CPF_SUPERVISOR) REFERENCES MEDICO (CPF)
);
/