CREATE TABLE HOSPITAL(
    CNES_HOSPITAL VARCHAR2(20),
    NOME VARCHAR2(20),
    CEP VARCHAR2(8),
    LOGRADOURO VARCHAR2(100),
    CONSTRAINT HOSPITAL_PKEY PRIMARY KEY (CNES_HOSPITAL)
);
/
CREATE TABLE ATENDENTE (
    CPF VARCHAR2(11),
    RAMAL VARCHAR2(3),
    NOME VARCHAR2(20),
    DATA_NASC DATE,
    CNES_ATENDENTE VARCHAR2(20) NOT NULL,
    CONSTRAINT ATENDENTE_PKEY PRIMARY KEY (CPF),
    CONSTRAINT ATENDENTE_FKEY FOREIGN KEY (CNES_ATENDENTE) REFERENCES HOSPITAL (CNES_HOSPITAL)
);
/

CREATE TABLE PACIENTE (
    CPF VARCHAR2 (11) ,
    NOME VARCHAR2 (20),
    DATA_NASC DATE,
    CPF_ATENDENTE VARCHAR2(11),
    GENERO VARCHAR2(20),
    CONSTRAINT PACIENTE_PKEY PRIMARY KEY (CPF),
    CONSTRAINT PAC_ATEND_FKEY FOREIGN KEY (CPF_ATENDENTE) REFERENCES ATENDENTE (CPF)
);
/
CREATE TABLE MEDICAMENTO(
    LOTE VARCHAR2(60),
    NOME VARCHAR2(20),
    VALIDADE DATE,
    CONSTRAINT MEDICAMENTO_PKEY PRIMARY KEY (LOTE)
);
/

CREATE TABLE ENFERMEIRO(
    CPF VARCHAR2(11),
    CATEGORIA VARCHAR2(20),
    NOME_ENFERMEIRO VARCHAR2(20),
    DATA_NASC DATE,
    CNES_ENFERMEIRO VARCHAR2(20) NOT NULL,
    CONSTRAINT ENFERMEIRO_PKEY PRIMARY KEY (CPF),
    CONSTRAINT ENFERMEIRO_FKEY FOREIGN KEY (CNES_ENFERMEIRO) REFERENCES HOSPITAL(CNES_HOSPITAL)
);
/
CREATE TABLE MEDICO (
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    DATA_NASC DATE,
    ESPECIALIDADE VARCHAR2(25),
    CPF_SUPERVISOR VARCHAR2(11),
    CNES_MEDICO VARCHAR2 (20) NOT NULL,
    CONSTRAINT MEDICO_PKEY PRIMARY KEY (CPF),
    CONSTRAINT MEDICO_FKEY1 FOREIGN KEY (CNES_MEDICO) REFERENCES HOSPITAL (CNES_HOSPITAL),
    CONSTRAINT MEDICO_FKEY2 FOREIGN KEY (CPF_SUPERVISOR) REFERENCES MEDICO (CPF)
);
/

CREATE TABLE GERENCIAMENTO(
	CPF_MEDICO VARCHAR(11),
    CONSTRAINT GERENCIAMENTO_FKEY FOREIGN KEY (CPF_MEDICO) REFERENCES MEDICO (CPF)
);

CREATE TABLE ARMAZENAMENTO (
    CNES_ARMAZENAMENTO VARCHAR2(20),
    LOTE VARCHAR2(30),
    NOME VARCHAR2(30),
    QTD INT DEFAULT 0,
    CONSTRAINT QTD CHECK (QTD > -1),
    CONSTRAINT ARMAZENAMENTO_PKEY PRIMARY KEY (CNES_ARMAZENAMENTO, LOTE),
    CONSTRAINT ARMAZENAMENTO_FKEY1 FOREIGN KEY (CNES_ARMAZENAMENTO) REFERENCES HOSPITAL (CNES_HOSPITAL),
    CONSTRAINT ARMAZENAMENTO_FKEY2 FOREIGN KEY (LOTE) REFERENCES MEDICAMENTO (LOTE)
);

CREATE TABLE CONSULTA (
    CPF_MEDICO VARCHAR2(11),
    CPF_PACIENTE VARCHAR2(11),
    TIMESTAMP_CONSULTA TIMESTAMP,
    CONSTRAINT CONSULTA_PKEY PRIMARY KEY (CPF_MEDICO, CPF_PACIENTE, TIMESTAMP_CONSULTA),
    CONSTRAINT CONSULTA_FKEY FOREIGN KEY (CPF_MEDICO) REFERENCES MEDICO(CPF),
    CONSTRAINT CCONSULTA_FKEY FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF)
);

CREATE TABLE TRATAMENTO(
    LOTE VARCHAR2(60),
    CPF_PACIENTE VARCHAR2(11),
    CPF_ENFERMEIRO VARCHAR2(11),
    TIMESTAMP_TRATAMENTO TIMESTAMP,
    CONSTRAINT TRATAMENTO_PKEY PRIMARY KEY (LOTE, CPF_PACIENTE, CPF_ENFERMEIRO, TIMESTAMP_TRATAMENTO),
    CONSTRAINT TRATAMENTO_FKEY1 FOREIGN KEY (LOTE) REFERENCES MEDICAMENTO (LOTE),
    CONSTRAINT TRATAMENTO_FKEY2 FOREIGN KEY (CPF_ENFERMEIRO) REFERENCES ENFERMEIRO (CPF),
    CONSTRAINT TRATAMENTO_FKEY3 FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE (CPF)
);

CREATE TABLE PRESCRICAO (
    CPF_MEDICO VARCHAR2(11),
    CPF_PACIENTE VARCHAR2(11),
    LOTE VARCHAR2(60),
    TIMESTAMP_PRESCRICAO TIMESTAMP,
    CONSTRAINT PRESCRICAO_PKEY PRIMARY KEY (CPF_MEDICO, CPF_PACIENTE,  TIMESTAMP_PRESCRICAO, LOTE),
    CONSTRAINT PRESCRICAO_FKEY1 FOREIGN KEY (CPF_MEDICO, CPF_PACIENTE, TIMESTAMP_PRESCRICAO) REFERENCES CONSULTA (CPF_MEDICO, CPF_PACIENTE, TIMESTAMP_CONSULTA),
    CONSTRAINT PRESCRICAO_FKEY2 FOREIGN KEY (LOTE) REFERENCES MEDICAMENTO (LOTE)
);
